version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  importer:
    build:
      context: .
      dockerfile: ./Dockerfile.importer
    container_name: importer
    depends_on:
      - mongo
    volumes:
      - .:/app
  
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    container_name: fastapi
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    container_name: vue-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mongo_data:
