version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  importer:
    build: .
    container_name: importer
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo_data:
